Updated cost figure
mosaicml/composer pull request #1180
Opened 2022-06-16 19:53 UTC by nqn

2022-06-17 01:41 UTC, ravi-mosaicml approved these changes
LGTM; see comments.

2022-06-17 01:41 UTC, ravi-mosaicml commented on README.md
> +  <a href="https://storage.googleapis.com/docs.mosaicml.com/images/composer_graph_dark_06162022.svg#gh-dark-mode-only" class="only-dark">
The link should be to the light mode version -- see above comment in the code.

```suggestion
  <a href="https://storage.googleapis.com/docs.mosaicml.com/images/composer_graph_light_06162022.svg#gh-dark-mode-only" class="only-dark">
```

2022-06-17 23:32 UTC, hanlint approved these changes

2022-06-17 23:33 UTC, hanlint requested changes
Ah, sorry one nit -- it needs the units (dollars)

2022-06-21 19:02 UTC, hanlint approved these changes

2022-06-22 20:04 UTC, merged