Don't download HF Model Config if specified
mosaicml/composer pull request #1291
Opened 2022-07-15 00:56 UTC by moinnadeem

The refactor of the HF integration downloads the model config if specified. We want to avoid this, so if the user has specified custom values, we should avoid loading the pretrained config.

2022-07-15 03:24 UTC, A-Jacobson commented on composer/models/bert/model.py
> +        if len(model_config) == 0:
```suggestion
        if not model_config:
```
this should be `None` or a `dict`. are we concerned about users passing an empty dict? (an empty dict == `None` btw)

2022-07-15 03:24 UTC, A-Jacobson commented on composer/models/bert/model.py
> +        if len(model_config) == 1:
```suggestion
        if model_config:
```

2022-07-15 03:25 UTC, A-Jacobson commented on composer/models/gpt2/model.py
> +        if len(model_config) == 0:
```suggestion
        if model_config == None:
```

2022-07-15 03:32 UTC, A-Jacobson requested changes
fix if user passes dictionary of length > 1

2022-08-03 18:32 UTC, ravi-mosaicml commented
@moinnadeem curious about the status of this PR?

2022-08-03 18:34 UTC, moinnadeem commented
@ravi-mosaicml I need to reconsider it -- a customer liked this, and I'm undoing a change they liked. Let me get back to you today

2022-08-11 21:26 UTC, hanlint commented
Closing as stale -- @moinnadeem please re-open if needed.

2022-08-11 21:26 UTC, closed without merging