update memory monitor
mosaicml/composer pull request #1940
Opened 2023-02-03 16:52 UTC by mvpatel2000

# What does this PR do?

Updates memory monitor to use GB, which is much more readable. Also fixes it to track current allocated memory instead of cumulative (which isn't really useful)

# What issue(s) does this change relate to?

[CO-1740](https://mosaicml.atlassian.net/browse/CO-1740)- Related to #1234

2023-02-03 18:08 UTC, dakinggg commented on composer/callbacks/memory_monitor.py
> +                memory_report[name.replace('bytes', 'gigabytes')] = memory_stats[torch_name] / 1e9
should this be rounded to some number of decimals?

2023-02-03 21:00 UTC, bandish-shah commented
Could we post an example of the new output before we're ready to merge this PR in the description?

2023-02-03 21:25 UTC, dakinggg requested changes
Blocking to look at the output and approve

2023-02-08 03:29 UTC, mvpatel2000 commented
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/17102158/217422042-f0448bf5-c5b1-4e00-975b-4d541090a285.png">

2023-02-08 08:00 UTC, dakinggg reviewed
Could you also paste in what this looks like when you log to console? Otherwise LGTM and will approve after that.

2023-02-08 19:04 UTC, mvpatel2000 commented
```[epoch=1][batch=96/390]:
	 Train trainer/global_step: 95
	 Train trainer/batch_idx: 95
	 Train memory/allocated_mem: 22.9840
	 Train memory/active_mem: 22.9840
	 Train memory/inactive_mem: 5.3172
	 Train memory/reserved_mem: 38.9250
	 Train memory/alloc_retries: 0
	 Train trainer/device_train_microbatch_size: 10
	 Train loss/train/total: 0.1528
	 Train wall_clock/train: 627.0995
	 Train wall_clock/val: 0.0000
	 Train wall_clock/total: 627.0995```

2023-02-08 22:46 UTC, merged