Adding filtering for optimizer parameters to only trainable parameters
mosaicml/composer pull request #2355
Opened 2023-07-07 15:26 UTC by bcui19

# What does this PR do?
After FSDP-ing the model, the optimizer should only contain parameters that require gradients (non-frozen parameters). This change is nice for LORA

# What issue(s) does this change relate to?
https://mosaicml.atlassian.net/browse/CO-2221

# Before submitting
- [ ] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [x ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

2023-07-07 20:12 UTC, danbider commented
looks good! will make fsdp lighter for models with some frozen weights

2023-07-18 00:21 UTC, mvpatel2000 approved these changes

2023-07-18 00:28 UTC, dakinggg requested changes
Discussed with Brandon that we would wait on this until it shows some benefit, just to avoid unnecessary changes.

2024-03-13 18:28 UTC, mvpatel2000 commented
Closing as out of date

2024-03-13 18:28 UTC, closed without merging