[Do not merge] Add FSDP custom wrap with torch 2.1
mosaicml/composer pull request #2460
Opened 2023-08-22 04:41 UTC by mvpatel2000

# What does this PR do?

Adds FSDP custom wrap with torch 2.1. Code snippets have been pulled off dev and will be used for benchmarking. This PR will not be merged until release candidate stabilizes on torch side.

# What issue(s) does this change relate to?

[GRT-2310](https://mosaicml.atlassian.net/browse/GRT-2310)

2023-08-22 04:46 UTC, vchiley commented on composer/trainer/mosaic_fsdp.py
>  elif version.parse(torch.__version__) >= version.parse('2.1.0'):
```suggestion
elif version.parse(torch.__version__) >= version.parse('2.1.1'):
```

2023-09-07 23:30 UTC, dakinggg approved these changes
Didn't really review the actual fsdp patch. assume you've got that covered

2023-09-07 23:30 UTC, dakinggg commented on composer/trainer/mosaic_fsdp.py
> +        # Monkey path for torch < 2.0 ie torch == 1.13.1
```suggestion
        # Monkey patch for torch < 2.0 ie torch == 1.13.1
```

2023-09-07 23:31 UTC, dakinggg reviewed
it would be nice though if you indicated what was changed from the original torch code in each of the modified functions

2023-09-08 03:03 UTC, b-chu requested changes
I didn't check your patch implementation; let me know if you want me to. Can you also add more details in the PR description of what/how exactly you're patching?

2023-09-08 03:03 UTC, b-chu commented on composer/trainer/mosaic_fsdp_utils.py
> +    """Modified version of https://github.com/pytorch/pytorch/blob/8292b03c47fd71beb23ae834971e044aef6f4d7c/torch/distributed/fsdp/_wrap_utils.py#L25.
Also it'd be helpful to explicitly say what torch version is required (check consistency with _custom_recursive_wrap_t2p0p1 docustring).

2023-09-08 03:03 UTC, b-chu commented on composer/trainer/mosaic_fsdp_utils.py
> +    def init_fn_t2p1p0(
Same as above.

2023-09-08 03:03 UTC, b-chu commented on setup.py
> -    'torch>=1.13.1,<2.1.1',
Why is this change needed?

2023-09-08 17:06 UTC, mvpatel2000 commented on composer/trainer/mosaic_fsdp_utils.py
> +def _custom_recursive_wrap_t2p1p0(
I would rather not. I would rather copy paste the torch code and not try to refactor their code

2023-09-08 17:08 UTC, mvpatel2000 commented on composer/trainer/mosaic_fsdp_utils.py
> +        # decide if we need to wrap the current module,
torch comment, resolving

2023-09-08 17:56 UTC, b-chu requested changes

2023-09-08 17:56 UTC, b-chu commented on composer/trainer/mosaic_fsdp_utils.py
> +            # CHANGE: We modify the original code to support custom FSDP kwargs and add
Can you add a similar comment to these functions as well?

_custom_recursive_wrap_t1p13p1
custom_auto_wrap_t1p13p1
_custom_recursive_wrap_t2p0p1
init_fn_t2p0p1
_custom_auto_wrap_t2p0p1
_custom_auto_wrap_t2p1p0
init_fn_t2p1p0

2023-09-08 18:51 UTC, b-chu approved these changes
Thanks Mihir!

2023-09-08 21:20 UTC, merged