Add script to validate remote object store paths
mosaicml/composer pull request #2667
Opened 2023-10-24 18:06 UTC by irenedea

# What does this PR do?

Adds a script that validates remote object store paths using composer utility functions. 

This is helpful for debugging especially on remote runs.

# What issue(s) does this change relate to?

# Before submitting
- [ ] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [ ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

2023-10-24 18:08 UTC, j316chuck commented
qq: Is this script supposed to be used locally?

2023-10-24 18:09 UTC, j316chuck approved these changes

2023-10-24 18:11 UTC, irenedea commented
@j316chuck the mcli yaml that i was using only supports s3, so i figured this would be an easy way to check all backends easily and through composer as well. Though, if this script fails, it doesn't necessarily rule out composer issues. I'll write an mcli yaml for this as well.

2023-10-24 18:24 UTC, dakinggg requested changes
Can we make this part of the library instead of a script? similar to `composer_collect_env`

2023-10-24 18:44 UTC, irenedea commented
@dakinggg good suggestion! so it would both in the library as well as a script, yeah?

2023-10-24 18:48 UTC, dakinggg commented
Yeah, exact same as composer_collect_env setup

2023-10-24 19:33 UTC, irenedea commented
@dakinggg I think the best move would be to create a `list_remote_objects` (that does exactly what the script does now, but returns a list of objects if objects are found). This would probably belong in `file_helpers.py`. If we add this function to `file_helpers.py`, do you have any thoughts on where to put the script?

2023-10-24 19:40 UTC, dakinggg commented
Can you define `console_scripts` that don't use `main`? It kinda looks like you can, but I've never tried it. If so, can just define a function in `file_helpers.py` that prints out what you want, and define the `console_scripts` command to point to that function

2023-10-24 20:30 UTC, irenedea commented
@dakinggg Tried it, but it won't work--it needs to a be a function that takes no arguments. So we could (1) keep a tiny script in `scripts/validate_remote_path.py` and have it call the `list_remote_objects` function in `file_helpers.py` (2) create a small function that takes no args that is defined in `file_helpers.py` that acts as  a console script

2023-10-24 22:29 UTC, dakinggg commented
I think Its possible to set it up with args parsed by argparse. because the `composer` launcher is set up the same way. See the main function in there that parses args

2023-10-25 02:18 UTC, irenedea commented on setup.py
> +              'composer_validate_remote_path = composer.utils.file_helpers:validate_remote_path'
validated that this works
```
composer_validate_remote_path oci://<path>
```

2023-10-25 02:49 UTC, dakinggg approved these changes

2023-10-25 02:49 UTC, dakinggg commented on setup.py
> +              'composer_validate_remote_path = composer.utils.file_helpers:validate_remote_path'
add back trailing comma so this is formatted nicely

2023-10-25 02:49 UTC, dakinggg commented on composer/utils/file_helpers.py
> +    If a the remote path is valid, prints a list of objects at the path.
```suggestion
    If the remote path is valid, prints a list of objects at the path.
```

2023-10-25 04:52 UTC, merged