Properly handle empty metric_names passed to Trainer._filter_metrics
mosaicml/composer pull request #2700
Opened 2023-11-08 22:23 UTC by irenedea

# What does this PR do?
Addresses error using `use_train_metrics: false`: `KeyError: 'continuation_indices'`
Manual test runs:
no fix: empty-eval-gFgK8Q 
with fix: empty-eval-with-fix-wpQHSK 

Previously, if `metric_names` is an empty list, we return `metrics` without filtering. This is incorrect as an empty list should signify no metrics. 

Additionally, we do not need to handle the case where `metric_names` is None. All usages in composer call `_filter_metrics` on `Evaluator.metric_names`, which is always a list. 

# What issue(s) does this change relate to?

# Before submitting
- [ ] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [ ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

2023-11-08 22:56 UTC, irenedea commented
TODO: see why it's causing a test failure

2023-11-09 00:57 UTC, irenedea commented on composer/core/evaluator.py
> +        self.metric_names = metric_names
this preserves `metric_names` as `None`

2023-11-09 04:16 UTC, mvpatel2000 requested changes
1. Can you add a unit test for this?
2. The PR changes the effective public API by changing the behavior of what happens when you don't specify metric_names. I think that's not intended -- we should still default to all metrics if none are specified (putting aside the concerns of the current API design of deepcopying metrics etc...). What if we did a milder change -- keep behavior as-is for `None`, and instead filter all if user list is `[]`?

2023-11-09 04:16 UTC, mvpatel2000 commented on composer/trainer/trainer.py
> -        return metrics
Issue is `not []` evaluates to `True`. Instead, this should be `if metric_names is None`.

@dakinggg  this is your favorite kind of bug

2023-11-09 15:26 UTC, irenedea commented
@mvpatel2000 Actually I think it does preserve the original intended behavior. What happens around the [callsites](https://github.com/mosaicml/composer/blob/3830a55fa4676701fe6c4ca6dbbe6ed447e10218/composer/trainer/trainer.py#L1204) for `_filter_metrics` is the following:
(1) Upon instantiation of an evaluator, evaluator.metric_names is None by default. (Previously, it was an empty list by default, so it was problematic that we weren't able to differentiate because default and empty list.)
(2) `ensure_evaluator(evaluator, default_metrics=model_metric_names)` is called for each evaluator. I made the change that this should populate the evaluator with the defaults (aka all metrics) if not set yet. It seemed appropriate given the call parameters.
(3) `evaluator.metric_names` is now populated with defaults and used in `_filter_metrics`

2023-11-09 15:30 UTC, irenedea commented
Hm, though on second thought, it could be nicer to just not populate the defaults in ensure_evaluator, so we only need to edit _filter_metrics and evaluator init. The biggest thing was that evaluator.metric_names was never None previously, so we never actually differentiated between emtpy list and defaults.

2023-11-09 16:07 UTC, mvpatel2000 approved these changes
LGTM! Thanks for hunting this down :)

2023-11-09 16:34 UTC, merged