refactor train_batch
mosaicml/composer pull request #2820
Opened 2024-01-05 08:01 UTC by sakshigupta93

# What does this PR do?

# What issue(s) does this change relate to?

# Before submitting
- [ ] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [ ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

2024-01-09 21:30 UTC, b-chu requested changes
Thanks for the PR!

2024-01-09 21:30 UTC, b-chu commented on composer/trainer/trainer.py
> +    def train_batch(self, batch: Any, use_grad_scaling: bool, last_wct: Optional[Any]) -> Any:
last_wct should be typed

2024-01-09 21:30 UTC, b-chu commented on composer/trainer/trainer.py
>          """Compute loss by training on a full batch of data.
Improve this docstring by adding args, returns, and the new functionality

2024-01-17 16:28 UTC, b-chu approved these changes
Thanks for the PR Sakshi!

2024-01-17 17:09 UTC, eracah commented
Also I think there are some setup items in fit that we need to add to train batch that get called the first time the user calls fit

2024-03-19 20:40 UTC, closed without merging