Update `NeptuneLogger`
mosaicml/composer pull request #3165
Opened 2024-04-02 16:30 UTC by AleksanderWWW

# What does this PR do?

# What issue(s) does this change relate to?

# Before submitting
- [ ] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [ ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

2024-04-03 08:36 UTC, AleksanderWWW commented
https://github.com/mosaicml/composer/issues/3170

@SiddhantSadangi @normandy7

2024-04-10 21:53 UTC, mvpatel2000 reviewed
LGTM, though would like Cheng to review too given other changes

2024-04-10 21:53 UTC, mvpatel2000 commented
@AleksanderWWW  can you please provide a proper PR description?

2024-04-10 21:57 UTC, cli99 reviewed
LGTM.

2024-04-13 14:34 UTC, mvpatel2000 commented
@AleksanderWWW  can approve and merge once tests pass. Let me know if you have any trouble

2024-04-15 15:35 UTC, AleksanderWWW commented
Idk, tried so many things but no idea how to fix this doctest failure due to unexpected output generated by neptune @mvpatel2000 
@SiddhantSadangi

2024-04-15 16:29 UTC, SiddhantSadangi requested changes
Let's remove suppressing logs before we forget doing so :)

2024-04-15 16:29 UTC, SiddhantSadangi commented on docs/source/trainer/file_uploading.rst
> +
We shouldn't be suppressing outputs in the docs code

```suggestion
    from composer.loggers import NeptuneLogger
    from composer import Trainer

```

2024-04-15 16:29 UTC, SiddhantSadangi commented on docs/source/trainer/logging.rst
> +    logging.getLogger("neptune").setLevel(logging.CRITICAL)
Same as above

```suggestion
```

2024-04-15 16:31 UTC, SiddhantSadangi commented
The error doesn't seem to related to Neptune outputs
`ERROR: Error in "testcode" directive: invalid option block`

The block is the same as our previous PR that cleared tests though 🤷

2024-04-15 16:34 UTC, SiddhantSadangi requested changes

2024-04-15 16:34 UTC, SiddhantSadangi commented on docs/source/trainer/logging.rst
> +    logging.getLogger("neptune").setLevel(logging.CRITICAL)
Same as before
```suggestion
    from composer import Trainer
    from composer.loggers import WandBLogger, CometMLLogger, MLFlowLogger, NeptuneLogger, FileLogger

```

2024-04-15 18:10 UTC, AleksanderWWW commented
Ok, idk how, but removing `logging.getLogger` and level setting + adding a whitespace here and there seemed to resolve the issue. I will definetely wake up tomorrow morning a little wiser and a lot more confused than I used to be.

2024-04-15 19:56 UTC, mvpatel2000 approved these changes
LGTM, a few minor nits I will apply

2024-04-15 19:56 UTC, mvpatel2000 commented on composer/callbacks/oom_observer.py
> +
```suggestion
```

2024-04-15 19:56 UTC, mvpatel2000 commented on tests/loggers/test_neptune_logger.py
> +        mock_scale_img.reset_mock()
```suggestion
    for image in image_variants:
        test_neptune_logger.log_images(images=image)
        mock_scale_img.assert_called_once()
        mock_scale_img.reset_mock()
```

2024-04-15 19:56 UTC, mvpatel2000 commented on tests/loggers/test_neptune_logger.py
> +
```suggestion
```

2024-04-15 19:56 UTC, mvpatel2000 commented on tests/loggers/test_neptune_logger.py
> +    assert not test_neptune_logger.neptune_run.exists(f'{test_neptune_logger._base_namespace}/test_symlink')
```suggestion
def test_neptune_logger_doesnt_upload_symlinks(test_neptune_logger, dummy_state):
    with _manage_symlink_creation('test.txt') as symlink_name:
        test_neptune_logger.upload_file(
            state=dummy_state,
            remote_file_name='test_symlink',
            file_path=Path(symlink_name),
        )
    assert not test_neptune_logger.neptune_run.exists(f'{test_neptune_logger._base_namespace}/test_symlink')
```

2024-04-15 20:05 UTC, mvpatel2000 commented
@AleksanderWWW  the following issue is causing test failures:
```
Expected nothing
Got:
Warning:     [neptune] [warning] Info (NVML): NVML Shared Library Not Found. GPU usage metrics may not be reported. For more information, see https://docs.neptune.ai/help/nvml_error/
```
is there a way to pass args to neptune to not emit warnings in this case? or does it have to be filtered

2024-04-15 20:51 UTC, mvpatel2000 commented
Hm... it might be flakey... I reran and it's gone 🤔. I will rerun one more time. If it passes we can merge and if it flakes post-merge ill revert and reopen PR

2024-04-15 21:30 UTC, merged