Add pre-built wheel for flash attention 2.7.0
mosaicml/composer pull request #3711
Opened 2024-11-14 16:40 UTC by j316chuck

# What does this PR do?
Add pre-built wheel for flash attention 2.7.0 which speeds up attention build by over 3+ hours. 

# What issue(s) does this change relate to?
Old docker builds were taking forever.

2024-11-14 17:00 UTC, mvpatel2000 approved these changes

2024-11-14 17:57 UTC, j316chuck commented
Holding off on this PR since this has the potential to break some PR's:
https://databricks.slack.com/archives/C05RUQNSFL2/p1731574998171059

2024-12-02 20:26 UTC, snarayan21 requested changes
need v2.6.3, as 2.7 is breaking (see here: https://github.com/mosaicml/llm-foundry/pull/1656)

2025-03-05 19:18 UTC, KuuCi commented
Closing this as it's getting replaced here:
https://github.com/mosaicml/composer/pull/3772

2025-03-05 19:18 UTC, closed without merging