[WIP] models docstrings
mosaicml/composer pull request #469
Opened 2022-02-11 08:47 UTC by A-Jacobson

#401 
- not sure how far i should go with the `loss.py`, `initializers.py` and model architecture files. The first two probably need a good refactor, it not outright deletion (these aren't exactly user facing). The model architectures are copied from all over the place. Am adding docstrings but am reluctant to refactor. Our `ComposerModel` versions should be the public facing interface for these. 

- unsure about module level docstring, should i do something like this? https://docs.mosaicml.com/en/v0.3.1/models.html. or link to the incoming model cards that @ajaysaini725  is writing to cover the model descriptions.

2022-02-15 17:36 UTC, ravi-mosaicml commented
> * not sure how far i should go with the `loss.py`, `initializers.py` and model architecture files. The first two probably need a good refactor, loss -> metrics and initializers -> (not sure, maybe deletion). The model architectures are copied from all over the place. Am adding docstrings but am reluctant to refactor. Our `ComposerModel` versions should be the public facing interface for these.

If a refactor is desperately needed, then let's do it. For PR review, though, could this refactor be done separately?


> * unsure about module level docstring, should i do something like this? https://docs.mosaicml.com/en/v0.3.1/models.html. or link to the incoming model cards that @ajaysaini725  is writing to cover the model descriptions.

A stub that would link to the model cards works.

2022-02-16 16:17 UTC, hanlint commented
Thanks for putting this together! A few comments:

`ComposerModel`:
- [ ] Can you add more information to the `ComposerModel` base class docstrings? e.g. especially the coupling of forward/loss and validate/metrics.
- [ ] `forward`: its worth mentiong that the input is from the dataloader. we want to tell folks as much about our trainer loop logic as possible. same thing for loss -- say that outputs come from forward, and batch from the dataloader
- [ ] `metrics`: similarly explain that the metrics shuld be torchmetrics. The "warning" should hide the torchmetrics link (e.g. See torchmetrics[link] for more details). Mention that one can return multiple metrics that would all be evaluated on the eval_dataloader.

- [] `ComposerTransformer` docstring should also be expanded with more information about how it works and example usages
- [] same for TIMM, BERT, ResNet, GPTmodel, etc, we need some code blocks that show its usage, and more detail on how it works.
- [] TIMM has some formatting issues with `testcode` and also the `model_name` and links in the parameters. See: https://mosaicml-composer--469.com.readthedocs.build/en/469/api_reference/composer.models.timm.model.html#composer.models.timm.model.Timm

2022-02-22 18:48 UTC, hanlint commented
This is ready for a re-review: cc: @hanlint @ravi-mosaicml

2022-02-22 22:55 UTC, ravi-mosaicml commented
I took a quick look at https://mosaicml-composer--469.com.readthedocs.build/en/469/api_reference/composer.models.html and noticed that many model-level docstrings and `__all__` are not defined. In addition, many references are not auto-linking (set `nitpicky = True` in `conf.py` to get the full list.

Let me know when I should take another look.

2022-02-22 22:56 UTC, ravi-mosaicml requested changes
Requesting changes for module-level docstrings, `__all__`, and another pass on fixing broken references.

2022-02-23 02:20 UTC, A-Jacobson commented
> I took a quick look at https://mosaicml-composer--469.com.readthedocs.build/en/469/api_reference/composer.models.html and noticed that many model-level docstrings and `__all__` are not defined. In addition, many references are not auto-linking (set `nitpicky = True` in `conf.py` to get the full list.
> 
> Let me know when I should take another look.

There are many objects in here I don't want to expose to a user such as Hparams and model objects copied from other repos that our `composermodels` wrap. I didn't write docstrings for these. I don't think I can exclude them with `__all__` either because we export them for our model registery in `trainer_hparams`. Do you have a suggestion for what to do about these?

2022-02-23 17:19 UTC, ravi-mosaicml commented
> There are many objects in here I don't want to expose to a user such as Hparams and model objects copied from other repos that our `composermodels` wrap. I didn't write docstrings for these. I don't think I can exclude them with `__all__` either because we export them for our model registery in `trainer_hparams`. Do you have a suggestion for what to do about these?

Hparams should be exposed; #558 helped format how these are documented. Every field in an hparam class should be listed under the Params section of the docstring, but for each field, it is fine to have a one-liner that points to the underlying class. See https://docs.mosaicml.com/en/latest/api_reference/composer.callbacks.callback_hparams.html#module-composer.callbacks.callback_hparams as an example.

For model objects from other repos, are they imports, or did we copy and paste the code? Imports need not be listed in `__all__`, since one should import from the source package (not composer). If we copied and pasted the code, then we are responsible for the code now, and as such, it should have docstrings and be brought up to our standards.

2022-02-24 11:38 UTC, A-Jacobson commented
> Hparams should be exposed; #558 helped format how these are documented. Every field in an hparam class should be listed under the Params section of the docstring, but for each field, it is fine to have a one-liner that points to the underlying class. See https://docs.mosaicml.com/en/latest/api_reference/composer.callbacks.callback_hparams.html#module-composer.callbacks.callback_hparams as an example.
> 
- Exposed and documented Hparams.

> For model objects from other repos, are they imports, or did we copy and paste the code? Imports need not be listed in `__all__`, since one should import from the source package (not composer). If we copied and pasted the code, then we are responsible for the code now, and as such, it should have docstrings and be brought up to our standards.

- Much of the code is copy and pasted and I suspect a some doesn't need to be here. I gave the main models docstrings and set some helper files to private. I'm going to have to do a larger refactor PR to bring all the copied code up to our standards.. which I do have planned. Hopefully this will do for a start.

- defined __all__ in every module + public file.

- fixed many broken links, there are still some that are broken when i run `nitpicky = True` locally. The broken ones are all external modules such as `torchmetrics.collections.MetricCollection`, builtin typing objections, torch, torchvision, and transformers objects. Are these supposed to work? I see these linked in our sphinx config. @ravi-mosaicml

2022-03-01 16:07 UTC, ravi-mosaicml commented
> * fixed many broken links, there are still some that are broken when i run `nitpicky = True` locally. The broken ones are all external modules such as `torchmetrics.collections.MetricCollection`, builtin typing objections, torch, torchvision, and transformers objects. Are these supposed to work? I see these linked in our sphinx config. @ravi-mosaicml

Can you look into the internsphinx inventory and see what the proper path for these elements are? See https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#showing-all-links-of-an-intersphinx-mapping-file. OK to defer this one to later -- if so please create a seperate issue for it.

> * The `forward` method of `ComposerModel` isn't showing in the docs and I'm not sure why. Perhaps it's because we subclass `torch.nn.Module`?

Forward is excluded in the sphinx config. Would adding a `:meta public:` force it to be documented?

2022-03-01 16:20 UTC, hanlint reviewed
This PR is a lot, thanks for doing this. Made several comments. Some major comments are:

* for brevity in the code, please use the global scope e.g. `.ComposerModel` instead of the full path `~composer....`. 
* defaults should be formatted as Default: True, not Default = True.

2022-03-01 16:20 UTC, hanlint commented on composer/models/__init__.py
> +See the ComposerModel docs for more details.
Should like to the docs with `:doc:` here.

2022-03-01 16:20 UTC, hanlint commented on composer/models/base.py
> +    """The interface needed to use a pytorch model with :class:`~composer.trainer.trainer.Trainer`.
```suggestion
    """The interface needed to use a pytorch model with :class:`.Trainer`.
```

2022-03-01 16:20 UTC, hanlint commented on composer/models/base.py
> +    To create a :class:`~composer.trainer.trainer.Trainer` compatible model, subclass :class:`~composer.models.base.ComposerModel` and
```suggestion
    To create a :class:`.Trainer` compatible model, subclass :class:`~composer.models.base.ComposerModel` and
```

2022-03-01 16:20 UTC, hanlint commented on composer/models/base.py
> +                return F.cross_entropy(outputs, targets)
Should additionally add the same as above -> For more detail, see the composer model docs (with a :doc: link)

2022-03-01 16:20 UTC, hanlint commented on composer/models/base.py
> +                     batch of data that may have to be unpacked.
```suggestion
                     batch of data that has to be unpacked.
```

2022-03-01 16:20 UTC, hanlint commented on composer/models/base.py
> +        """Get metrics for evaluating the model. Metrics should be torchmetrics compatible for accurate distributed
```suggestion
        """Get metrics for evaluating the model. Metrics should be :class:`torchmetrics.Metrics` compatible for accurate distributed
```

2022-03-01 16:20 UTC, hanlint commented on composer/models/base.py
> +                return outputs, targets # return a tuple of (``outputs``, ``targets``)
```suggestion
                return outputs, targets # return a tuple of (outputs, targets)
```

code block, not RST

2022-03-01 16:20 UTC, hanlint commented on composer/models/base.py
> +        How validate outputs are passed to :meth:`metrics` (pseudocode):
```suggestion
        This pseudocode illustrates how validate outputs are passed to :meth:`metrics`:
```

2022-03-01 16:20 UTC, hanlint commented on composer/models/base.py
> +    """A convenience class that creates a :class:`~composer.models.base.ComposerModel` for classification tasks from a
here and throughout should use the global scope `.ComposerModel` and `.ComposerClassifier` to make the docstrings more less verbose.

2022-03-01 16:20 UTC, hanlint commented on composer/models/bert/model.py
> +                that the model expects, as found in :meth:`composer.models.transformer_shared.ComposerTransformer.get_model_inputs`.
```suggestion
                that the model expects, as found in :meth:`.ComposerTransformer.get_model_inputs`.
```

2022-03-01 16:20 UTC, hanlint commented on composer/models/classify_mnist/model.py
>      """A simple convolutional neural network extending :class:`ComposerClassifier`.
```suggestion
    """A simple convolutional neural network extending :class:`.ComposerClassifier`.
```

2022-03-01 16:20 UTC, hanlint commented on composer/models/classify_mnist/model.py
> +    :class:`~composer.models.classify_mnist.model.MNIST_Classifier` is a simple example
```suggestion
    A simple example
```
(self-referencing)

2022-03-01 16:20 UTC, hanlint commented on composer/models/deeplabv3/deeplabv3.py
> +    """DeepLabV3 model extending :class:`~composer.models.base.ComposerClassifier`. Logs Mean Intersection over Union
```suggestion
    """DeepLabV3 model extending :class:`.ComposerClassifier`. Logs Mean Intersection over Union
```

2022-03-01 16:20 UTC, hanlint commented on composer/models/deeplabv3/deeplabv3_hparams.py
> +    """yahp interface for :class:`~composer.models.deeplabv3.deeplabv3.ComposerDeepLabV3`. This class specifies
```suggestion
    """yahp interface for :class:`~.ComposerDeepLabV3`. This class specifies
```

2022-03-01 21:21 UTC, A-Jacobson commented
> This PR is a lot, thanks for doing this. Made several comments. Some major comments are:
> 
> * for brevity in the code, please use the global scope e.g. `.ComposerModel` instead of the full path `~composer....`.
> * defaults should be formatted as Default: True, not Default = True.

Thanks for going through it. Comments should be addressed.

2022-03-02 16:09 UTC, hanlint approved these changes
Agreed that the `loss` and `initializers` will need a better organization moving forward (already captured in #536 ), but that should not be blocking for this PR.

However, one major request -- for all docstrings, arguments that have defaults should be listed as optional. eg. in `Timm`, should be:

```
pretrained (bool, optional): Imagenet pretrained. Default: False.
```
Can you do a pass through all the methods in this module and add optional wherever appropriate?

2022-03-08 21:31 UTC, growlix reviewed
99% of my comments are one of the following four comments:

1. Example and default arguments should always be formatted like ``"this"``.
2. Consistent reference formatting
3. No nude hyperlinks—embed hyperlinks in descriptive text
4. File-level docstrings

I'm sorry that we have to inflict this violence on each other. But impeccable documentation requires blood sacrifice.

2022-03-08 21:31 UTC, growlix commented on composer/models/unet/__init__.py
> +"""The Unet architecture used in image segmentation. The example we are using is for medical brain tumor data.
The 2nd sentence could be a bit more specific. The example dataset?

2022-03-08 21:31 UTC, growlix commented on composer/models/unet/model.py
> +        normalization_layer (str): normalization layer type, one of ("batch", "instance").
```suggestion
        normalization_layer (str): normalization layer type, one of (``"batch"``, ``"instance"``).
```

2022-03-08 21:31 UTC, growlix commented on composer/models/unet/model.py
> +        dimension (int): filter dimensions.
Capitalize first letter of parameter description

2022-03-08 21:31 UTC, growlix commented on composer/models/unet/model.py
>  ## Code adapted from https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/nnUNet/
File-level docstring

2022-03-08 21:31 UTC, growlix commented on composer/models/unet/unet.py
>  # Copyright 2021 MosaicML. All Rights Reserved.
File-level docstring

2022-03-08 21:31 UTC, growlix commented on composer/models/unet/unet.py
> +        num_classes (int): The number of classes. Needed for classification tasks. Default: 3.
```suggestion
        num_classes (int): The number of classes. Needed for classification tasks. Default: ``3``.
```

2022-03-08 21:31 UTC, growlix commented on composer/models/unet/unet.py
> +    See this `paper <https://arxiv.org/abs/1505.04597>`_ for details on the
Reference format

2022-03-08 21:31 UTC, growlix commented on composer/models/unet/model.py
> +    https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/nnUNet/.
embed link

2022-03-08 21:31 UTC, growlix commented on composer/models/unet/unet_hparams.py
>  # Copyright 2021 MosaicML. All Rights Reserved.
File-level docstring

2022-03-08 21:31 UTC, growlix commented on composer/models/unet/unet_hparams.py
> +        num_classes (int, optional): The number of classes. Needed for classification tasks. Default: 3.
```suggestion
        num_classes (int, optional): The number of classes. Needed for classification tasks. Default: ``3``.
```

2022-03-09 00:36 UTC, A-Jacobson commented on composer/models/base.py
> +        .. code-block:: python
Going to punt the doctests in the base class to another pr as they require fixtures.

2022-03-09 00:38 UTC, A-Jacobson commented on composer/models/base.py
> +        :meth:`__init__`. This format enables accurate distributed logging. Metrics consume the outputs of
I'm referring to the sub class init here. Not sure how to link to that as it doesn't exist yet :(. Base class doesn't have an init.

2022-03-09 00:44 UTC, A-Jacobson commented on composer/models/loss.py
> +        target (torch.Tensor) : If containing class indices, shape :math:`(N)` where each value is
It should! This is the pytorch docstring with some minor modifications

2022-03-09 06:36 UTC, A-Jacobson commented on composer/models/base.py
> +    .. code-block:: python
gonna punt this to another PR, ravi and i discussed these.

2022-03-09 07:04 UTC, A-Jacobson commented on composer/models/base.py
> +            batch (~composer.core.types.Batch): The output batch from dataloader.
have tried a few things to fix this. was unable to. Also these are going to be removed soon anyway so I didn't want to burn too much time on it.

2022-03-09 07:22 UTC, A-Jacobson commented on composer/models/deeplabv3/deeplabv3.py
beyond    

 """Helper function to build a torchvision DeepLabV3 model with a 3x3 convolution layer and dropout removed."""
 
 ?

2022-03-09 07:26 UTC, A-Jacobson commented on composer/models/deeplabv3/deeplabv3.py
>  class ComposerDeepLabV3(ComposerModel):
only that I didn't want to add a refactor to this already huge PR. see https://github.com/mosaicml/composer/issues/536

2022-03-09 09:22 UTC, A-Jacobson commented on composer/models/base.py
> +                :meth:`~torchmetrics.Metric.update` methods of the metrics returned by :meth:`metrics`.
yeah a lot of torchmetrics links are broken. The package authors don't have working links of it either. https://torchmetrics.readthedocs.io/en/latest/references/modules.html?highlight=Metrics . not sure what to do about this.

2022-03-09 09:25 UTC, A-Jacobson commented on composer/models/bert/model.py
> +        module (transformers.BertModel): An instance of BertModel that
same as torchmetrics, I believe transformers doesn't have a compatible RTD table i'm not sure how to get them to work.

2022-03-09 09:36 UTC, A-Jacobson commented on composer/models/nlp_metrics.py
>              output (Mapping): The output from the model, which must contain
Have tried a few path variations with no luck. any ideas on this?

2022-03-09 09:46 UTC, A-Jacobson commented on composer/models/nlp_metrics.py
>      State:
saw the slack discussion on this but it doesn't look like there's a great solution. either set as attributes or ignore it for now?

2022-03-09 11:56 UTC, A-Jacobson commented
Done:

- Added all file level docstrings.
- embedding links.
- added all the `` marks...everywhere.
- vit docstrings, sorta minimal.
- bare minimum ssd docstrings.
- refactored effecientnet to hide non user-facing blocks.

Not Done:
- some links are still broken: transformers, base types, some torchmetrics. These broken links don't have readthedocs paths available for us to you. I've linked to the relevant documentation or github pages for some. For other's i've left alone either because we're working to remove them (Batch types), or they're in an awkward place to add a normal link (Return or Args). Open to suggestions here but I do think it's ok to send this off without them.
- codeblocks -> doctests in abstract classes, punting to a later PR as they require fixtures + some are psuedocode.
- `State` formatting on metrics, adding them as attrs will cause more trouble than living with the less pretty formatting for now.
- SSD is a lot.. I know it's not perfect but I'd like to get this PR moving before even more models appear.

@growlix I choose you!

2022-03-09 20:42 UTC, growlix commented
Looking greaet, Austin. Hope your eyes/fingers aren't too bloody.

> embedded paper links, they are cited as [Name](Link) not [Name](link)(Author et al, Date). Should i do (Author et al, Date)? Is there a relatively painless way to get this information?

I'd go [Name](link)(Author et al, Date) if possible; [Author et al, Date](link) is also acceptable. I think author attribution is the most important part. Unfortunately I don't know if there's an easy way to do this other than clicking through to the actual page.

> some links are still broken: transformers, base types, some torchmetrics. These broken links don't have readthedocs paths available for us. I've linked to the relevant documentation or github pages for some. I've left others alone either because we're working to remove them (Batch types), or they're in an awkward place to add a normal link (Return or Args). Open to suggestions here but I do think it's ok to send this off without them.

Agree. I think you can leave as-is.

> codeblocks -> doctests in abstract classes, punting to a later PR as they require fixtures + some are psuedocode.

Sounds good, just remember to file an issue.

> SSD is a lot.. I know it's not perfect but I'd like to get this PR moving before even more models appear.

I'll double check for anything egregious, but otherwise sounds good, file an issue.

> State formatting on metrics, adding them as attrs will cause more trouble than living with the less pretty formatting for now.

As per [Bandish's suggestion](https://mosaicml.slack.com/archives/C02F05H39SL/p1646773237565229?thread_ts=1646768731.433729&cid=C02F05H39SL), I think you can just move the state info to a new paragraph in the summary and preface it with something like

```
Adds the following attributes to :class:`composer.core.state`:
```
(Don't quote my syntax on that)

Unfortunately I think the current rendering is a bit too sloppy.

> general refactoring (standardizing module naming and layout) is being punted to here, https://github.com/mosaicml/composer/issues/536. This PR is already too crazy, lets end the pain.

+ 1

2022-03-09 21:40 UTC, A-Jacobson commented
- author attribution in.
- state information moved above params on `nlp_metrics` not sure this is prettier but it's done.
- issue filed for codeblocks -> testcode https://github.com/mosaicml/composer/issues/703
- issue filed for ssd cleanup https://github.com/mosaicml/composer/issues/704

2022-03-09 21:48 UTC, growlix approved these changes
SSD files need `__all__`, but otherwise looks p good

2022-03-09 21:50 UTC, A-Jacobson commented on composer/models/ssd/ssd.py
> +"""Single Shot Object detection Model with pretrained ResNet34 backbone extending :class:`.ComposerModel`."""
im cool with it.

2022-03-09 22:36 UTC, merged