[XS] Consolidating NLP Import Message
mosaicml/composer pull request #795
Opened 2022-03-21 20:02 UTC by moinnadeem

Moves the "Composer was installed without NLP utilities" to a shared file instead of repeating the message in multiple places

2022-03-21 20:32 UTC, growlix approved these changes
`NLP_IMPORT_ERROR_MESSAGE` might be more informative than `NLP_IMPORT_MESSAGE`, but your call.

2022-03-21 20:32 UTC, growlix commented on composer/utils/dynamic_import.py
> +NLP_IMPORT_MESSAGE = textwrap.dedent("""\
`NLP_IMPORT_ERROR_MESSAGE` might be more informative than `NLP_IMPORT_MESSAGE`.

2022-03-21 20:39 UTC, ravi-mosaicml requested changes
I'm hesitant to hardcode nlp stuff in composer.utils. Intead, would it instead be possible to write a helper exception class like this, which could then live in `composer.utils`?

```python

class MissingCondinalImportError(ImportError):
   def __init__(extra_deps_group: str, conda_pacakge: str, conda_channel: str = "conda-forge")`
      ...
```
Then, we can do `raise MissingCondinalImportError(...) from e`.

2022-03-21 22:03 UTC, ravi-mosaicml approved these changes
LGTM, though:
1. Rename `composer.utils.dynamic_import` to `composer.utils.import_helpers`
2. Re-export `MissingConditionalImportError` on `composer.utils.__init__`

2022-03-21 22:31 UTC, ravi-mosaicml commented on composer/utils/__init__.py
> +from composer.utils.import_helpers import MissingConditionalImportError, import_object
nit: add this to `__all__` below

2022-03-22 01:30 UTC, moinnadeem commented on composer/utils/__init__.py
> +from composer.utils.import_helpers import MissingConditionalImportError, import_object
Done!

2022-03-22 11:34 UTC, merged